TrailerAZ/Areas/TrailerAZdashboard/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess;
using Entities;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using TrailerAZ.ViewModels;

namespace TrailerAZ.Areas.TrailerAZdashboard.Controllers
{
    [Area("TrailerAZdashboard")]
    public class ActorsController : Controller
    {
        private readonly TvContext _context;
        private readonly IWebHostEnvironment _environment;

        public ActorsController(TvContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: TrailerAZdashboard/Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.actors.ToListAsync());
        }

        // GET: TrailerAZdashboard/Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.actors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // GET: TrailerAZdashboard/Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TrailerAZdashboard/Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( ActorCreateVM actorVM, IFormFile photo, IFormFile coverPhoto)
        {

            Actor actor = new()
            {
                Name = actorVM.Name,
                Wikipedia = actorVM.Wikipedia,
                Photo = actorVM.Photo.ToString(),
                CoverPhoto = actorVM.CoverPhoto.ToString(),
                IsFeatured = actorVM.IsFeatured,
                InstagramLink = actorVM.InstagramLink,
                FacebookLink = actorVM.FacebookLink,
                TwitterLink = actorVM.TwitterLink

            };
            if (ModelState.IsValid)
            {
                if (photo != null)
                {
                    var fileName = Guid.NewGuid() + photo.FileName;
                    var wwwFolder = Path.Combine(_environment.WebRootPath, "assets/img/actor");
                    var imgFolder = Path.Combine(wwwFolder, fileName);
                    using var FileStream = new FileStream(imgFolder, FileMode.Create);
                    photo.CopyTo(FileStream);
                    actor.Photo = "/assets/img/actor/" + fileName;

                }
                if (coverPhoto != null)
                {
                    var fileName = Guid.NewGuid() + coverPhoto.FileName;
                    var wwwFolder = Path.Combine(_environment.WebRootPath, "assets/img/actor");
                    var imgFolder = Path.Combine(wwwFolder, fileName);
                    using var FileStream = new FileStream(imgFolder, FileMode.Create);
                    photo.CopyTo(FileStream);
                    actor.CoverPhoto = "/assets/img/actor/" + fileName;

                }
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: TrailerAZdashboard/Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.actors.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: TrailerAZdashboard/Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormFile photo, IFormFile coverPhoto,  Actor actor)
        {
            if (id != actor.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (photo != null)
                    {
                        var fileName = Guid.NewGuid() + photo.FileName;
                        var wwwFolder = Path.Combine(_environment.WebRootPath, "assets/img/actor");
                        var imgFolder = Path.Combine(wwwFolder, fileName);
                        using var FileStream = new FileStream(imgFolder, FileMode.Create);
                        photo.CopyTo(FileStream);
                        actor.Photo = "/assets/img/actor/" + fileName;

                    }
                    if (coverPhoto != null)
                    {
                        var fileName = Guid.NewGuid() + coverPhoto.FileName;
                        var wwwFolder = Path.Combine(_environment.WebRootPath, "assets/img/actor");
                        var imgFolder = Path.Combine(wwwFolder, fileName);
                        using var FileStream = new FileStream(imgFolder, FileMode.Create);
                        photo.CopyTo(FileStream);
                        actor.CoverPhoto = "/assets/img/actor/" + fileName;

                    }
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: TrailerAZdashboard/Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.actors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: TrailerAZdashboard/Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.actors.FindAsync(id);
            _context.actors.Remove(actor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.actors.Any(e => e.ID == id);
        }
    }
}

TrailerAZ/Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrailerAZ.ViewModels;

namespace TrailerAZ.Controllers
{
    public class ActorController : Controller
    {
        private readonly ActorService _actorService;

        public ActorController(ActorService actorService)
        {
            _actorService = actorService;
        }

        public IActionResult Index()
        {
            ActorVM actorVM = new()
            {
                ActorIsFeatured = _actorService.GetActorsIsFetaured(),
                Actors = _actorService.GetActors(),
            };
            return View(actorVM);
        }

        public IActionResult Details(int? id)
        {
            if (id == null) return NotFound();

           var byActor = _actorService.GetActorByID(id.Value);

            if (byActor == null) return NotFound();

            ActorVM actorVM = new()
            {
                GetActor = byActor,
                SerialToActors = _actorService.serialToActors(id.Value),
                filmToActors = _actorService.GetFilmToActors(id.Value),
                FilmIsLeadRole = _actorService.FilmIsLeadRole(),

            };

            return View(actorVM);
        }
        public IActionResult FindActor(int skipCount)
        {
            var actor = _actorService.AllActor(skipCount).Take(1).ToList();

            ActorVM actorVM = new()
            {

                AllActor = actor
            };
            return PartialView(actorVM);
        }
    }
}

TrailerAZ/Controllers/FilmController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrailerAZ.ViewModels;

namespace TrailerAZ.Controllers
{
    public class FilmController : Controller
    {
        private readonly FilmService _filmService;

        public FilmController(FilmService filmService)
        {
            _filmService = filmService;
        }

        public IActionResult Index()
        {
            FilmDetailVM filmVM = new()
            {
                GetFilms = _filmService.FilmsIsFeatured(),
                GetFilmsIsTrending = _filmService.FilmIsTrending(),
                GetFilmIsMostView = _filmService.FilmIsMostView(),
                GetFilmIsNew = _filmService.FilmIsNew(),
                AllFilms = _filmService.AllFilms(),

            };
            return View(filmVM);
        }

        public IActionResult Details(int? id)
        {
            if (id == null) return NotFound();

            var byFilm = _filmService.GetFilmByID(id.Value);
            var samecat = _filmService.SameCategoryFilm(id.Value);
            if (byFilm == null) return NotFound();

            FilmDetailVM filmDetailVM = new()
            {
                ByFilm = byFilm,
                GetFilmsIsFeatured = _filmService.GetFilmsIsFeatured(id.Value),
                SameCategoryFilms = samecat,
                filmToCategories = _filmService.GetFilmToCategories(id.Value)


            };

            return View(filmDetailVM);
        }
    }
}

TrailerAZ/Controllers/SerialController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrailerAZ.ViewModels;

namespace TrailerAZ.Controllers
{
    public class SerialController : Controller
    {
        private readonly SerialService _serialService;

        public SerialController(SerialService serialService)
        {
            _serialService = serialService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FindSeriaForSeason(int? seasonId,int? id)
        {
            var serials= _serialService.GetSerialSeria(id.Value,seasonId.Value);
            return PartialView("_SeriaPartial",serials);
        }


        public IActionResult Details(int? id,int? seriaId)
        {
            SerialVM serialVM = new();
            if (!id.HasValue && !seriaId.HasValue) return NotFound();
            if (id.HasValue)
            {
                var bySerial = _serialService.GetSerialByID(id.Value);
                if (bySerial == null) return NotFound();

                serialVM.SerialId = id;
                serialVM.Serial = bySerial;
                serialVM.Serie = bySerial.SerialSeasons[0].SerialSeries[0];
            }
            if (seriaId.HasValue)
            {
                var bySerie = _serialService.GetSeriaByID(seriaId.Value);
                if (bySerie == null) return NotFound();
                serialVM.Serie = bySerie;
            }

            serialVM.SameCategorySerial = _serialService.SameCategorySerial(id?? (int)serialVM.Serie.SerialID);
            serialVM.serialToCategories = _serialService.GetSerialToCategories(id ?? (int)serialVM.Serie.SerialID);
            serialVM.GetserialIsFeatured = _serialService.GetSerialsFeatured(id ?? (int)serialVM.Serie.SerialID);
            return View(serialVM);
        }
    }
}

TrailerAZ/Views/Actor/Details.cshtml
@section Styles{
    <link rel="stylesheet" href="~/assets/css/actorDetail.css">

}

@model ActorVM


<!--Main start-->

<main>


    <section class="about-actor">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5 col-xxl-5">
                    <div class="left">
                        <img class="img-fluid"
                             src="@Model.GetActor.CoverPhoto" alt="">
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-7 col-lg-7 col-xl-7 col-xxl-7">
                    <div class="right">
                        <div class="name">
                            <h2>@Model.GetActor.Name</h2>
                        </div>
                        <div class="actor-text">
                            <p>
                                @Model.GetActor.Wikipedia
                            </p>

                        </div>
                        <div class="social-acc">
                            <h6>Actors social accounts</h6>
                            <a target="_blank" href="@Model.GetActor.InstagramLink"><i class="fab fa-instagram"></i></a>
                            <a target="_blank" href="@Model.GetActor.FacebookLink"><i class="fab fa-facebook"></i></a>
                            <a target="_blank" href="@Model.GetActor.TwitterLink"><i class="fab fa-twitter"></i></a>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- serie starting start -->
    @if (Model.SerialToActors.Count > 0 && Model.SerialToActors != null)
    {
        <section id="PluginOne" class="serieStart-slider">
            <div class="container">
                <div class="row">
                    <div class="card-name">
                        <h3>TV series starring</h3>
                    </div>
                    <div class="all">
                        @foreach (var actorSerial in Model.SerialToActors)
                        {
                            <div class="card-film">

                                <img style="height:300px;" src="@actorSerial.Serial.Photo"
                                     alt="">
                                <div class="card-text">
                                    <a href="@Url.Action("Details","Serial", new {id=actorSerial.ID })"><i class="play-btn fad fa-play-circle"></i></a>
                                    <h5 style="display: none;">@actorSerial.Serial.Name</h5>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </section>

    }

    <!-- serie starting end -->
    <!-- serie starting start -->

    @if (Model.FilmIsLeadRole.Count != 0)
    {
        <section style="@(Model.FilmIsLeadRole.Count==0? "display:none;": null)" id="PluginOne" class="leadSerie-slider">
            <div class="container">
                <div class="row">
                    <div class="card-name">
                        <h3>Lead role TV series</h3>
                    </div>
                    <div class="all">
                        @foreach (var leadRole in Model.FilmIsLeadRole)
                        {
                            <div class="card-film">

                                <img style="height:300px" src="@leadRole.Film.Photo"
                                     alt="">
                                <div class="card-text">
                                    <a href="@Url.Action("Details","Film", new {id=leadRole.FilmID })"><i class="play-btn fad fa-play-circle"></i></a>
                                    <h5 style="display: none;">@leadRole.Film.Name</h5>
                                </div>
                            </div>
                        }



                    </div>
                </div>
            </div>
        </section>
    }


    <!-- serie starting end -->
    <!-- film start -->
    @if (Model.filmToActors.Count != 0)
    {
        <section id="PluginOne" class="film-slider">
            <div class="container">
                <div class="row">
                    <div class="card-name">
                        <h3>Films Starring</h3>
                    </div>
                    <div class="all">
                        @foreach (var film in Model.filmToActors)
                        {
                            <div class="card-film">

                                <img style="height:300px" src="@film.Film.Photo"
                                     alt="">
                                <div class="card-text">
                                    <a href="@Url.Action("Details","Film", new {id=film.FilmID })"><i class="play-btn fad fa-play-circle"></i></a>
                                    <h5 style="display: none;">@film.Film.Name</h5>
                                </div>
                            </div>
                        }



                    </div>
                </div>
            </div>
        </section>
    }


    <!-- film end -->

</main>

<!--Main end-->


@section Scripts{

    <script src="~/assets/js/actorDetail.js"></script>

}

TrailerAZ/Views/Actor/Index.cshtml
@model ActorVM

@section Styles{

    <link rel="stylesheet" href="~/assets/css/actor.css">

}


<!-- Search section start -->

<section class="search">
    <div class="container">
        <div class="row">
            <div class="search-item ">
                <input class="search-inp " type="search" name="Search-Film " id="" placeholder="Search Actor...">
                <input class="submit-btn " type="submit" value="search">

            </div>
        </div>
    </div>
</section>

<!-- Search section End -->
<!--  favorite actors start -->

<section style="@(Model.ActorIsFeatured.Count==0? "display:none;" : null)" id="PluginOne" class="actor-slider">
    <div class="container">
        <div class="row">
            <div class="card-name">
                <h3>Favorite Actors</h3>
            </div>
            <div class="all">
                @foreach (var actor in Model.ActorIsFeatured)
                {
                    <div class="card-actor">

                        <img src="@actor.Photo" alt="">
                        <div class="card-text">
                            <a href="@Url.Action("Details","Actor", new { id=actor.ID})"><i class="play-btn fas fa-info-circle"></i></a>
                            <h5 style="display: none;">@actor.Name</h5>
                        </div>
                    </div>
                }



            </div>
        </div>
    </div>
</section>

<!-- favorite actors end -->
<!-- Actors start -->

<section class="actors">
    <div class="container">
        <div class="row">
            <div class="detail-head col-12 col-sm-12 col-md-12 col-xl-12 col-lg-12">
                <h4>Actors</h4>
            </div>
            @foreach (var actor in Model.Actors)
            {
                <div class="col-md-4 col-6 col-sm-4 col-lg-3 col-xl-3">
                    <div class="actor-detail">
                        <div class="detail-img">
                            <img class="img-fluid"
                                 src="@actor.Photo"
                                 alt="">

                        </div>
                        <div class="detail-text">
                            <h5>@actor.Name</h5>
                            <p><a href="@Url.Action("Details", "Actor", new { id=actor.ID})">Read More...</a></p>
                        </div>
                    </div>

                </div>
            }

           
                <div class="load-more col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <button>Load More</button>
                </div>
            

        </div>

    </div>
</section>

<!-- Actors End -->

@section Scripts{

    <script src="~/assets/js/actor.js"></script>

    <script>
        let skipCount = 0;
        $(".btnLoad").click(function () {
            skipCount += 1;
            $.ajax({
                url: "/Home/FindActor",
                data: { skipCount },
                type: "Json",
                success: function (e) {
                    console.log(e)
                    $("#actorArea .row").append(e)
                    if (e != null) {
                        $(".btnLoad").fadeIn();

                    }
                    else {
                        $(".btnLoad").fadeOut();
                    }
                }
            })
        })
    </script>

}